CREATE TABLE `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `union_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信UnionID',
  `openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信OpenID',
  `mobile` VARCHAR(20) NOT NULL COMMENT '手机号',
  `nickname` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户昵称',
  `avatar_url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像地址',
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'bcrypt密码哈希',
  `status` VARCHAR(20) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `last_login_at` DATETIME NULL DEFAULT NULL COMMENT '最后登录时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_mobile` (`mobile`),
  UNIQUE KEY `uk_users_openid` (`openid`),
  KEY `idx_users_union_id` (`union_id`),
  KEY `idx_users_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='C端用户表';

CREATE TABLE `doctors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(64) NOT NULL COMMENT '医生姓名',
  `mobile` VARCHAR(20) NOT NULL COMMENT '手机号',
  `title` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '医生职称',
  `department` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '科室',
  `introduction` TEXT NULL COMMENT '医生简介',
  `employee_no` VARCHAR(32) NOT NULL COMMENT '工号',
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'bcrypt密码哈希',
  `status` VARCHAR(20) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `last_login_at` DATETIME NULL DEFAULT NULL COMMENT '最后登录时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_doctors_mobile` (`mobile`),
  UNIQUE KEY `uk_doctors_employee_no` (`employee_no`),
  KEY `idx_doctors_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生表';

CREATE TABLE `consult_sessions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `session_no` VARCHAR(32) NOT NULL COMMENT '会话编号',
  `doctor_id` BIGINT UNSIGNED NOT NULL COMMENT '医生ID',
  `customer_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '顾客ID，首次加入后绑定',
  `room_id` INT NOT NULL COMMENT 'TRTC房间号，必须处于int32合法范围',
  `share_token` VARCHAR(128) NULL DEFAULT NULL COMMENT '分享令牌',
  `share_url_path` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '小程序分享路径',
  `status` VARCHAR(20) NOT NULL DEFAULT 'created' COMMENT '状态：created/shared/joined/in_consult/finished/expired/cancelled',
  `expired_at` DATETIME NOT NULL COMMENT '分享入口过期时间',
  `started_at` DATETIME NULL DEFAULT NULL COMMENT '开始面诊时间',
  `ended_at` DATETIME NULL DEFAULT NULL COMMENT '结束面诊时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consult_sessions_session_no` (`session_no`),
  UNIQUE KEY `uk_consult_sessions_room_id` (`room_id`),
  UNIQUE KEY `uk_consult_sessions_share_token` (`share_token`),
  KEY `idx_consult_sessions_doctor_id` (`doctor_id`),
  KEY `idx_consult_sessions_customer_id` (`customer_id`),
  KEY `idx_consult_sessions_status` (`status`),
  KEY `idx_consult_sessions_expired_at` (`expired_at`),
  CONSTRAINT `fk_consult_sessions_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`id`),
  CONSTRAINT `fk_consult_sessions_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='面诊会话表';

CREATE TABLE `consult_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `session_id` BIGINT UNSIGNED NOT NULL COMMENT '面诊会话ID',
  `customer_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '顾客ID',
  `doctor_id` BIGINT UNSIGNED NOT NULL COMMENT '医生ID',
  `summary` TEXT NOT NULL COMMENT '接诊摘要',
  `diagnosis` TEXT NOT NULL COMMENT '初步诊断',
  `advice` TEXT NOT NULL COMMENT '医生建议',
  `duration_seconds` BIGINT NOT NULL DEFAULT 0 COMMENT '面诊时长（秒）',
  `ended_at` DATETIME NOT NULL COMMENT '结束时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consult_records_session_id` (`session_id`),
  KEY `idx_consult_records_customer_id` (`customer_id`),
  KEY `idx_consult_records_doctor_id` (`doctor_id`),
  CONSTRAINT `fk_consult_records_session_id` FOREIGN KEY (`session_id`) REFERENCES `consult_sessions` (`id`),
  CONSTRAINT `fk_consult_records_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_consult_records_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='面诊记录表';
